package coachingmateanalytics.coachingmate.common.utils;

import lombok.Data;

/**
 * A utility class representing a search request with various filters and paging options.
 */
@Data
public class SearchRequest {
    private String tags;
    private String categories;
    private String keyword;
    private Paging paging;
    private String sorting;

    // Getters and setters are automatically generated by the Lombok @Data annotation.
}
